### ISSUE TITLE
Link Failed

### ISSUE THREAD

**Issue by willtuna** [rbgirshick/voc-dpm#19]
http://people.cs.uchicago.edu/~rbg/INRIA_PASCAL.tgz
This link has failed. I really need the annotation file

**Comment by rbgirshick** [comment]
The new URL is https://dl.dropboxusercontent.com/s/4j4ywd1e9onqwkw/INRIA_PASCAL.tgz?dl=0.

**Comment by willtuna** [comment]
Thanks for your support !Excuse me , how to use those .txt file ?
Since the annotation in the Pascal VOC are .xml file. Should I wrote a converter by myself ?

**Comment by rbgirshick** [comment]
Sorry, but I can't provide support for this kind of question. A quick pointer, though, is to look into the VOC 2007 devkit code which has support for the .txt file annotations.
