### ISSUE TITLE
Error using mex clang: error: unsupported option '-fopenmp'

### ISSUE THREAD

**Issue by acharles7** [rbgirshick/voc-dpm#27]
I am using macOS Mojave with MATLAB_R2018b. Is there a way I can use a different gcc version than the Xcode one?

**Comment by Emilycs09** [comment]
I have this problem too!

Have you resolve it?

**Comment by Emilycs09** [comment]
I have this problem too!

Have you solved it?

**Comment by acharles7** [comment]
NO

**Comment by Emilycs09** [comment]
In case you are interested, I altered to windows to run the code, and this error doesn't show up any more.

**Comment by acharles7** [comment]
Thanks:)
